checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  nodes:
    node-that-needs-docker:
      environment:
        docker: true
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      dependencies:
        override:
          - make build
          - make test80

      tests:
        override:
          - command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
